version: "3.8"

services:
  php:
    build: .
    ports:
      - "9090:80"
    depends_on:
      - mysql
    volumes:
      # Montar todo el código para desarrollo
      - .:/var/www/html
      # Volúmenes para archivos subidos (PERSISTENTES) con rutas absolutas
      - /svr/emavraforestal/uploads:/var/www/html/uploads
      - /svr/emavraforestal/qr_codes:/var/www/html/qr_codes
    environment:
      - PHP_DISPLAY_ERRORS=On
      - PHP_ERROR_REPORTING=E_ALL
    command: >
      bash -c "
        # Crear directorios si no existen
        mkdir -p /var/www/html/uploads/trees /var/www/html/uploads/pdfs /var/www/html/qr_codes &&
        # Asignar permisos
        chmod -R 777 /var/www/html/uploads /var/www/html/qr_codes &&
        # Cambiar propietario a www-data
        chown -R www-data:www-data /var/www/html &&
        # Iniciar Apache
        apache2-foreground
      "

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: reforest
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "9091:80"
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=rootpassword
      - MYSQL_ROOT_PASSWORD=rootpassword
    depends_on:
      - mysql

volumes:
  mysql-data: