version: "3.8"

services:
  php:
    build: .
    ports:
      - "9090:80"
    user: "www-data"
    volumes:
      # Volúmenes para archivos subidos (PERSISTENTES)
      - ./uploads:/var/www/html/uploads
      - ./qr_codes:/var/www/html/qr_codes
      # Montar todo el código para desarrollo
      - .:/var/www/html
    # Agregar red para comunicarse con MySQL local
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - PHP_DISPLAY_ERRORS=On
      - PHP_ERROR_REPORTING=E_ALL